import Head from 'next/head';
import Hero from '../components/Hero';
import { Section1 } from './components/section1';
import { Section2 } from '../components/Section2';
import { Section3 } from '../components/Section3';
import { Section4 } from '../components/Section4';
import { Section5 } from '../components/Section5';
import { Section6 } from '../components/Section6';
import { Section7 } from '../components/Section7';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Photography Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='Captur Photography' message='I capture moments in nature and keep them alive.' />

      <Section1 />
      <Section2 />
      <Section3 />
      <Section4 />
      <Section5 />
      <Section6 />
      <Section7 />

    </div>
  );
};
